
default: &default
  adapter: postgresql
  database: my_database_dev
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: my_database_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_dev
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: my_database_dev
  pool: 5
  timeout: 5000